version: '3'
services:
  web:
    container_name: invoices_dev
    build: .
    ports:
    - "127.0.0.1:9999:80"
    volumes:
    - .:/invoice-generator
  db:
    container_name: invoices_db
    image: mariadb:10.5
    ports:
    - "3333:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
    volumes:
    - db_data_invoices:/var/lib/mysql
volumes:
  db_data_invoices:

