version: '3'
services:
  web:
    container_name: invoices_dev
    build: .
    ports:
    - "127.0.0.1:9999:80"
    volumes:
    - .:/invoice-generator
  db:
    container_name: invoices_db
    image: mariadb:10.5
    ports:
    - "3333:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
    volumes:
    - db_data_invoices:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: user
      PMA_PASSWORD: password
    restart: always
    ports:
      - 8081:80
volumes:
  db_data_invoices:

